apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: locust
  namespace: locust
  labels:
    app: locust
    release: prometheus-grafana
spec:
  selector:
    matchLabels:
      app: locust
  endpoints:
  - port: prometheus
    path: /metrics
    interval: 15s
    scrapeTimeout: 10s
