apiVersion: v1
kind: Service
metadata:
  name: locust-master
  namespace: locust
  labels:
    app: locust
    component: master
spec:
  type: LoadBalancer  # Change to NodePort for cost savings (see guide)
  selector:
    app: locust
    component: master
  ports:
  - port: 8089
    targetPort: 8089
    protocol: TCP
    name: web-ui
  - port: 5557
    targetPort: 5557
    protocol: TCP
    name: master-communication
  sessionAffinity: ClientIP  # Sticky sessions for web UI
